name: les_loups_garous_de_tchernobyl
description: les_loups_garous_de_tchernobyl
publish_to: "none"

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^3.0.0
  socket_io_client: 3.1.2
  collection: ^1.19.1
  shared_preferences: ^2.5.3
  window_manager: ^0.5.1
  vibration: ^3.1.3
  meta: ^1.12.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true

# â† AU NIVEAU RACINE (pas sous `flutter`)
flutter_launcher_icons:
  android: "adaptive"
  ios: true
  image_path: assets/icon.png
  adaptive_icon_background: "#111111"
  adaptive_icon_foreground: assets/icon.png
  remove_alpha_ios: true
